version: "3"

services:
  app:
    image: signal:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - userData:/home/signal/.config/Signal/
      # - NODE_CONFIG_DIR:/opt/Signal/resources/app.asar/
    cap_add:
     - SYS_ADMIN

volumes:
  userData:
  # NODE_CONFIG_DIR: