version: "3"

services:
  app:
    image: signal:latest
    build: .
    environment:
      - XDG_RUNTIME_DIR=/tmp
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
    volumes:
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}
    cap_add:
     - SYS_ADMIN
     